// Supply Chain Dashboard indicator registry.
//
// Each entry is the single source of truth for one metric: where to pull it,
// how to display it, what it means, and how to read its trend.
//
// Fields:
//   id            : stable internal key (used in URLs for drill-downs)
//   source        : 'fred' | 'eia' | 'bls' | 'census' | 'yahoo' | 'derived' |
//                   'scrape:cass' | 'scrape:dat' | 'scrape:act-ftr' |
//                   'scrape:drewry' | 'scrape:scfi' | 'scrape:freightos' |
//                   'scrape:bdi' | 'scrape:shipbunker' | 'scrape:usps' |
//                   'scrape:aar' | 'scrape:ports' | 'scrape:nyfed-gscpi'
//   sourceId      : upstream id (FRED/EIA/BLS/Census), or yahoo ticker, or null
//   category      : 'dc' | 'industrial-re' | 'middle-mile' | 'last-mile' | 'international'
//   label         : full display name
//   shortLabel    : compact label for dense grids
//   unit          : display unit suffix
//   decimals      : display precision
//   freq          : 'daily' | 'weekly' | 'monthly' | 'quarterly' | 'annual'
//   transform     : 'level' | 'yoy' | 'mom_diff' | 'index100' | 'zscore'
//   release       : human-readable cadence note
//   direction     : 'higher_better' | 'lower_better' | 'neutral'
//                   (from the perspective of an operator/shipper)
//   longTermNormYears : window for "vs long-term norm"
//   whyMatters    : 60-120 words, shown in tooltip
//   howToRead     : 60-120 words, shown in tooltip
//   methodology   : longer prose, shown on drill-down page
//   hasVintages   : if true, drill-down fetches historical vintages
//   featured      : if true, surfaces on the category overview tile
//   composite     : if defined, this entry is computed from others
//                   { dependsOn: [ids], compute: descriptor }

export const CATEGORIES = {
  'dc':            { label: 'Distribution Center',       accent: '#3b82f6', order: 1 },
  'industrial-re': { label: 'Industrial Real Estate',    accent: '#8b5cf6', order: 2, parent: 'dc' },
  'middle-mile':   { label: 'Middle Mile',               accent: '#10b981', order: 3 },
  'last-mile':     { label: 'Last Mile',                 accent: '#f59e0b', order: 4 },
  'international': { label: 'International / Sourcing',  accent: '#ef4444', order: 5 },
};

export const INDICATORS = [

  // ============================================================================
  // DISTRIBUTION CENTER — operational economics of warehousing
  // ============================================================================
  {
    id: 'WAREHOUSE_AHE',
    source: 'fred', sourceId: 'CES4300000008',
    category: 'dc',
    label: 'Trade & Transp/Warehouse Avg Hourly Earnings',
    shortLabel: 'TTU Wage',
    unit: '$/hr', decimals: 2, freq: 'monthly', transform: 'level',
    release: 'BLS Current Employment Statistics, ~1st Friday of month',
    direction: 'lower_better',
    longTermNormYears: 10,
    whyMatters: 'Direct-labor wages are the largest single line item in distribution-center opex, typically 50-65% of variable cost. FRED publishes hourly earnings at the broader Trade, Transportation and Utilities sector — the cleanest public proxy for what a warehouse operator pays. Acceleration above 4% YoY historically presages either price pass-through to shippers (via storage rates) or productivity push (automation capex). Deceleration signals labor-market slack and pricing power for warehouse tenants.',
    howToRead: 'Above 10y norm and rising → margin pressure on operators; expect storage-rate increases at lease renewal and a wave of automation announcements within 2-3 quarters. At norm and rising slowly → pass-through environment, balanced. Below norm → labor available, capacity easy to staff, shipper-favorable. Watch the second derivative: wage acceleration cresting often precedes hiring freezes by 6 months.',
    methodology: 'BLS series CES4349300008 — Average Hourly Earnings of all employees in NAICS 4931 (Warehousing and Storage). Production-and-nonsupervisory employees only. Not seasonally adjusted at the sub-industry level. Released monthly with the Employment Situation report.',
  },
  {
    id: 'WAREHOUSE_AHE_YOY',
    source: 'derived',
    category: 'dc',
    label: 'Warehouse Wage YoY',
    shortLabel: 'Wage YoY',
    unit: '%', decimals: 1, freq: 'monthly', transform: 'level',
    release: 'Derived from CES4349300008',
    direction: 'lower_better',
    longTermNormYears: 10,
    featured: true,
    composite: { dependsOn: ['WAREHOUSE_AHE'], compute: 'yoy' },
    whyMatters: 'Year-over-year change in warehouse wages is the single best high-frequency read on labor-cost pressure for DC operators. A reading > 5% YoY for two or more consecutive prints has historically marked the onset of automation investment cycles (Amazon, Walmart, Prologis tenant capex). Sub-3% prints correlate with shipper-favorable warehousing rate environments.',
    howToRead: '> 5% YoY → cost pressure, expect rate pass-through. 3-5% → typical inflationary band, monitor. < 3% → soft labor market, operator-favorable. Compare against ECI (employment cost index) for context.',
    methodology: 'YoY % change of WAREHOUSE_AHE (CES4349300008), 12-month lookback.',
  },
  {
    id: 'WAREHOUSE_EMP',
    source: 'fred', sourceId: 'CES4349300001',
    category: 'dc',
    label: 'Warehousing & Storage Employment',
    shortLabel: 'Warehouse Emp',
    unit: 'k', decimals: 0, freq: 'monthly', transform: 'level',
    release: 'BLS CES, ~1st Friday',
    direction: 'higher_better',
    longTermNormYears: 10,
    whyMatters: 'Total headcount in NAICS 4931. Reflects aggregate DC capacity utilization and structural growth of the warehouse footprint. The series tripled from 700K to 1.95M between 2010 and 2022 as e-commerce reshaped fulfillment networks. Subsequent contraction to ~1.85M in 2024-25 marked the post-Amazon-overbuild absorption phase.',
    howToRead: 'Trending up with stable wage growth → healthy expansion. Trending up with accelerating wages → capacity-constrained, expect rate inflation. Trending down → either automation displacing labor or genuine demand softening. Cross-check with inventory-to-sales ratio to disambiguate.',
    methodology: 'BLS CEU4349300001 — All Employees, Warehousing and Storage. Seasonally adjusted by source.',
  },
  {
    id: 'JOLTS_TWU_OPENINGS',
    source: 'fred', sourceId: 'JTU480099JOL',
    category: 'dc',
    label: 'JOLTS: Transp/Warehouse/Utilities Openings',
    shortLabel: 'TWU Openings',
    unit: 'k', decimals: 0, freq: 'monthly', transform: 'level',
    release: 'BLS JOLTS, ~5 weeks after month-end',
    direction: 'neutral',
    longTermNormYears: 10,
    whyMatters: 'Job openings in transportation, warehousing, and utilities — the closest published JOLTS aggregate to supply-chain employment. Trend reflects how aggressively operators are trying to staff up. Openings ≈ headcount × 0.07 is the historical norm; > 0.10 signals tight labor; < 0.04 signals slack.',
    howToRead: 'Rising openings + flat hires = unfilled-demand wage pressure ahead. Rising openings + rising hires = healthy expansion. Falling openings = early signal of demand softening, leads warehouse employment by 1-2 quarters.',
    methodology: 'BLS JOLTS series JTS4400JOL. Monthly with revisions.',
  },
  {
    id: 'JOLTS_TWU_QUITS',
    source: 'fred', sourceId: 'JTU480099QUR',
    category: 'dc',
    label: 'JOLTS: TWU Quits Rate',
    shortLabel: 'TWU Quits',
    unit: '%', decimals: 1, freq: 'monthly', transform: 'level',
    release: 'BLS JOLTS, ~5 weeks after month-end',
    direction: 'lower_better',
    longTermNormYears: 10,
    whyMatters: 'Quits rate is the cleanest forward indicator of wage pressure in warehousing. Workers quit when they see better-paying alternatives nearby; the quits rate leads the wage growth series by 4-8 months. The 2021-22 spike to 3.5%+ telegraphed the wage acceleration that hit P&Ls through 2023.',
    howToRead: 'Above 3.0% → workers leveraging tight labor market, wage acceleration coming. 2.0-3.0% → typical band. Below 2.0% → workers staying put, wage pressure releasing.',
    methodology: 'BLS JOLTS series JTS4400QUR. Quits as % of total employment.',
  },
  {
    id: 'JOLTS_TWU_LAYOFFS',
    source: 'fred', sourceId: 'JTU480099LDR',
    category: 'dc',
    label: 'JOLTS: TWU Layoffs Rate',
    shortLabel: 'TWU Layoffs',
    unit: '%', decimals: 1, freq: 'monthly', transform: 'level',
    release: 'BLS JOLTS, ~5 weeks after month-end',
    direction: 'lower_better',
    longTermNormYears: 10,
    whyMatters: 'Layoffs rate signals operator distress. Spikes are rare in warehousing — even in 2008-09 the sector held employment relatively well — so a sustained move above 1.5% is a meaningful signal of demand contraction.',
    howToRead: 'Above 1.5% sustained → operator-side stress, demand contraction. 0.8-1.5% → normal churn band. Below 0.8% → operators hoarding labor.',
    methodology: 'BLS JOLTS series JTS4400LDR. Layoffs and discharges as % of employment.',
  },
  {
    id: 'PPI_CORRUGATED',
    source: 'fred', sourceId: 'WPU091503',
    category: 'dc',
    label: 'PPI: Corrugated Paperboard',
    shortLabel: 'Corrugated PPI',
    unit: '', decimals: 1, freq: 'monthly', transform: 'level',
    release: 'BLS PPI release, mid-month',
    direction: 'lower_better',
    longTermNormYears: 10,
    featured: true,
    whyMatters: 'Corrugated boxes are 8-12% of variable shipping cost for parcel-heavy operations and 3-5% for palletized DCs. Corrugated PPI tracks linerboard mill prices passed through by box plants. Containerboard supply is structurally tight (limited new mill capacity post-2020), so price moves are durable rather than transient. A 10% YoY rise typically translates to 2-3% inflation in fully-loaded shipping cost.',
    howToRead: 'Trending up with rising containerboard mill capacity utilization → durable price increase, plan for opex inflation. Trending up with capacity easing → likely transient. Trending down with falling demand → real concession environment, time to renegotiate box contracts.',
    methodology: 'BLS PPI series WPU091503 — Corrugated and Solid Fiber Boxes. Index, 1982=100.',
  },
  {
    id: 'PPI_PALLETS',
    source: 'fred', sourceId: 'WPU0841',
    category: 'dc',
    label: 'PPI: Wood Pallets',
    shortLabel: 'Pallets PPI',
    unit: '', decimals: 1, freq: 'monthly', transform: 'level',
    release: 'BLS PPI, mid-month',
    direction: 'lower_better',
    longTermNormYears: 10,
    whyMatters: 'Pallets are an underappreciated cost item — most DCs cycle 50-200K pallets per year. Whitewood (new) pallet prices track lumber and labor; recycled pallet prices follow whitewood with a ~3 month lag. The 2020-22 lumber spike hit pallet costs disproportionately because operators couldn\'t substitute.',
    howToRead: 'Track lumber as the leading driver. Whitewood prices > 30% above 5y mean → consider rental pool conversion (CHEP, PECO).',
    methodology: 'BLS PPI series WPU08321401 — Wood Pallets and Skids.',
  },
  {
    id: 'PPI_MAT_HANDLING',
    source: 'fred', sourceId: 'WPU114',
    category: 'dc',
    label: 'PPI: Material Handling Equipment',
    shortLabel: 'MHE PPI',
    unit: '', decimals: 1, freq: 'monthly', transform: 'level',
    release: 'BLS PPI, mid-month',
    direction: 'lower_better',
    longTermNormYears: 10,
    whyMatters: 'Captures forklifts, conveyors, racking, AS/RS systems. Capex inflation matters because automation pays back over 3-7 years; a 15% rise in MHE prices pushes equilibrium automation IRR below operator hurdle rates and slows projects. Conversely, equipment-cost deflation accelerates automation rollouts.',
    howToRead: 'Above 5% YoY → automation projects pencil less easily, expect deal pipeline to slow. Flat/down → window for capex.',
    methodology: 'BLS PPI series WPU114 — Material Handling Equipment.',
  },
  {
    id: 'PPI_WAREHOUSE_SVCS',
    source: 'fred', sourceId: 'PCU493493',
    category: 'dc',
    label: 'PPI: Warehousing & Storage Services',
    shortLabel: 'Warehouse Svc PPI',
    unit: '', decimals: 1, freq: 'monthly', transform: 'level',
    release: 'BLS PPI, mid-month',
    direction: 'neutral',
    longTermNormYears: 10,
    featured: true,
    whyMatters: 'The cleanest measure of contract-warehousing rate inflation — what 3PLs charge clients per pallet position, per month, or per pick. Lags wage and rent inflation by ~6-12 months as 3PL contracts roll. A spike here is the moment shippers feel the upstream cost stack.',
    howToRead: 'Rising fast and labor + rent rising → expect more rate increases. Rising while inputs ease → 3PL margin recovery phase. Falling → competitive bid environment, time to RFP.',
    methodology: 'BLS PPI series PCU493493 — Warehousing and Storage Services.',
  },
  {
    id: 'ELEC_INDUSTRIAL',
    source: 'eia', sourceId: 'ELEC_INDUSTRIAL',
    category: 'dc',
    label: 'Industrial Electricity Rate (US)',
    shortLabel: 'Ind. Electricity',
    unit: '¢/kWh', decimals: 2, freq: 'monthly', transform: 'level',
    release: 'EIA Electric Power Monthly, ~6 weeks after month-end',
    direction: 'lower_better',
    longTermNormYears: 10,
    whyMatters: 'Lighting, HVAC, conveyor drives, and battery charging make electricity 4-8% of DC variable cost (higher for cold storage at 12-20%). Industrial-sector rates are negotiated bilaterally but track the published average closely. Rising rates compress automation ROI and reward energy-efficient retrofits.',
    howToRead: 'YoY > 8% → cold-storage operators and high-throughput DCs face material margin pressure. Compare against natural-gas spot prices, which drive ~40% of US power generation.',
    methodology: 'EIA, electricity retail sales price for industrial sector, US average. Reported monthly.',
  },
  {
    id: 'INVENTORIES_TO_SALES',
    source: 'fred', sourceId: 'ISRATIO',
    category: 'dc',
    label: 'Inventories-to-Sales Ratio',
    shortLabel: 'Inv/Sales',
    unit: '', decimals: 2, freq: 'monthly', transform: 'level',
    release: 'Census MTIS, ~6 weeks after month-end',
    direction: 'neutral',
    longTermNormYears: 10,
    featured: true,
    whyMatters: 'The single most important macro signal for warehouse demand. Ratio > 1.4 historically signals inventory glut and is associated with declining warehousing tenant demand 2-3 quarters later. Ratio < 1.25 signals lean inventory and supports rising DC space demand. The 2022 surge to 1.45 telegraphed the 2023 industrial-RE absorption slowdown.',
    howToRead: '> 1.40 → over-inventoried, expect warehouse demand softening 1-2Q out, sub-let activity rising. 1.30-1.40 → balanced. < 1.25 → lean, restocking risk supports DC demand. Direction matters more than level.',
    methodology: 'Census Bureau Manufacturing and Trade: Inventories to Sales Ratio. Total business inventories divided by total business sales.',
  },
  {
    id: 'INV_MFG',
    source: 'fred', sourceId: 'MNFCTRIMSA',
    category: 'dc',
    label: 'Manufacturing Inventories',
    shortLabel: 'Mfg Inv',
    unit: '$M', decimals: 0, freq: 'monthly', transform: 'level',
    release: 'Census MTIS, ~6 weeks after month-end',
    direction: 'neutral',
    longTermNormYears: 10,
    whyMatters: 'Upstream inventory pipeline. Manufacturing inventory builds typically lead retail-side builds by 1-2 quarters. Inflection points here flag the start and end of inventory cycles before they show up at the consumer-facing level.',
    howToRead: 'Mfg inv accelerating while sales decelerating → unwind risk. Mfg inv flat while sales rising → supply tight, expect price pressure.',
    methodology: 'Census Manufacturers\' Total Inventories, seasonally adjusted, in millions of dollars.',
  },
  {
    id: 'INV_RETAIL',
    source: 'fred', sourceId: 'RETAILIMSA',
    category: 'dc',
    label: 'Retail Inventories',
    shortLabel: 'Retail Inv',
    unit: '$M', decimals: 0, freq: 'monthly', transform: 'level',
    release: 'Census MTIS, ~6 weeks after month-end',
    direction: 'neutral',
    longTermNormYears: 10,
    whyMatters: 'Retailer inventory health is the ultimate pull-side signal for the warehouse network. Building retail inventories above sales growth → over-stocking risk → warehouse demand follows.',
    howToRead: 'Retail inv YoY > sales YoY by > 5pp → over-stock, mark-down cycle ahead. < 0pp → restocking risk, DC demand supports.',
    methodology: 'Census Retail Trade Inventories, seasonally adjusted, millions of dollars.',
  },
  {
    id: 'INV_WHOLESALE',
    source: 'fred', sourceId: 'WHLSLRIMSA',
    category: 'dc',
    label: 'Wholesale Inventories',
    shortLabel: 'Whlsl Inv',
    unit: '$M', decimals: 0, freq: 'monthly', transform: 'level',
    release: 'Census MTIS, ~6 weeks after month-end',
    direction: 'neutral',
    longTermNormYears: 10,
    whyMatters: 'Bridges manufacturer and retailer inventories. Wholesale inventory builds reflect distributor confidence in downstream demand and absorption capacity in 3PL and merchant-wholesaler networks.',
    howToRead: 'Use as cross-check on retail and manufacturing inventories. Coherent build across all three = real inventory cycle. Divergence between segments = sector-specific dynamic.',
    methodology: 'Census Wholesale Trade Inventories, seasonally adjusted, millions of dollars.',
  },

  // ============================================================================
  // INDUSTRIAL REAL ESTATE — DC sub-deep-dive
  // ============================================================================
  {
    id: 'CONSTR_PRIVATE',
    source: 'fred', sourceId: 'TLPRVCONS',
    category: 'industrial-re',
    label: 'Total Private Construction Spending',
    shortLabel: 'Private Constr.',
    unit: '$M SAAR', decimals: 0, freq: 'monthly', transform: 'level',
    release: 'Census Construction Spending, ~5 weeks after month-end',
    direction: 'higher_better',
    longTermNormYears: 10,
    whyMatters: 'Aggregate private construction puts industrial activity in macro context. Industrial-specific lines move with this top line plus or minus.',
    howToRead: 'Use for context — pair with manufacturing construction (TLMFGCONS) for the industrial-specific signal.',
    methodology: 'Census, Total Private Construction Put in Place, monthly SAAR in millions of dollars.',
  },
  {
    id: 'CONSTR_MANUF',
    source: 'fred', sourceId: 'TLMFGCONS',
    category: 'industrial-re',
    label: 'Manufacturing Construction Spending',
    shortLabel: 'Mfg Constr.',
    unit: '$M SAAR', decimals: 0, freq: 'monthly', transform: 'level',
    release: 'Census Construction Spending, ~5 weeks after month-end',
    direction: 'higher_better',
    longTermNormYears: 10,
    featured: true,
    whyMatters: 'The CHIPS / IRA reshoring wave shows up here first. Manufacturing construction tripled from $80B SAAR (2020) to $240B SAAR (2024) as semiconductor fabs, EV battery plants, and clean-energy assembly ramped. Trend continuation = sustained industrial-RE demand near manufacturing nodes.',
    howToRead: 'Above $200B SAAR → reshoring cycle intact, expect industrial vacancy to stay tight near manufacturing hubs. Below $150B → deceleration; watch industrial REIT metro mix.',
    methodology: 'Census, Manufacturing Construction Put in Place, monthly SAAR in millions of dollars.',
  },
  {
    id: 'CRE_DELINQ',
    source: 'fred', sourceId: 'DRCRELEXFACBS',
    category: 'industrial-re',
    label: 'CRE Loan Delinquency Rate',
    shortLabel: 'CRE Delinq.',
    unit: '%', decimals: 2, freq: 'quarterly', transform: 'level',
    release: 'Federal Reserve, ~6 weeks after quarter-end',
    direction: 'lower_better',
    longTermNormYears: 10,
    whyMatters: 'Banks\' commercial real estate loan delinquency rate. Industrial-specific delinquencies are a fraction of office, but the aggregate signal warns of credit-market stress that bleeds into industrial pricing through cap-rate widening.',
    howToRead: 'Above 1.5% → broad CRE stress, expect cap rates to widen. Below 1.0% → benign. Industrial-specific delinquency typically runs ~50% of the aggregate.',
    methodology: 'Federal Reserve, Delinquency Rate on Commercial Real Estate Loans, All Commercial Banks (DRCRELACBS).',
  },
  {
    id: 'CRE_PRICES',
    source: 'fred', sourceId: 'COMREPUSQ159N',
    category: 'industrial-re',
    label: 'Commercial Real Estate Prices',
    shortLabel: 'CRE Prices',
    unit: '', decimals: 1, freq: 'quarterly', transform: 'level',
    release: 'BIS via FRED, quarterly',
    direction: 'higher_better',
    longTermNormYears: 10,
    whyMatters: 'BIS-published CRE price index for the US. Tracks broad CRE values; industrial-specific outperformed the index from 2018-22 then mean-reverted. Useful context for industrial REIT NAV discounts.',
    howToRead: 'Compare to industrial REIT price index — gap reveals public-market premium or discount to private CRE marks.',
    methodology: 'BIS Real Residential Property Prices for United States; the BIS-republished CRE-comparable series (COMREPUSQ159N).',
  },
  {
    id: 'REIT_INDUSTRIAL_BASKET',
    source: 'yahoo',
    sourceId: ['PLD', 'REXR', 'FR', 'STAG', 'EGP', 'TRNO'],
    category: 'industrial-re',
    label: 'Industrial REIT Basket (Equal-Weight)',
    shortLabel: 'Ind. REIT Basket',
    unit: '', decimals: 1, freq: 'daily', transform: 'index100',
    release: 'Daily, equity market close',
    direction: 'higher_better',
    longTermNormYears: 5,
    featured: true,
    whyMatters: 'Equal-weighted price index of the six largest US industrial REITs (Prologis, Rexford, First Industrial, STAG, EastGroup, Terreno). Public-market read on industrial-RE values, leads private-market cap rate moves by 6-12 months. The 2022 drawdown (~30%) telegraphed the 2023-24 cap-rate widening before private deals printed it.',
    howToRead: 'Drawdown from peak > 20% → expect private cap rates to widen 50-100bps over next 12 months. Sustained outperformance vs S&P → cap-rate compression cycle.',
    methodology: 'Equal-weighted total-return index of PLD, REXR, FR, STAG, EGP, TRNO. Rebased to 100 at series start. Daily closes from Yahoo Finance.',
  },
  {
    id: 'REIT_AVG_DIV_YIELD',
    source: 'yahoo',
    sourceId: ['PLD', 'REXR', 'FR', 'STAG', 'EGP', 'TRNO'],
    category: 'industrial-re',
    label: 'Industrial REIT Avg Dividend Yield',
    shortLabel: 'REIT Yield',
    unit: '%', decimals: 2, freq: 'daily', transform: 'level',
    release: 'Daily',
    direction: 'higher_better',
    longTermNormYears: 5,
    whyMatters: 'Trailing dividend yield averaged across the basket — a public-market proxy for industrial cap rate. Useful as a yield-spread reference against the 10Y Treasury for risk-premium analysis.',
    howToRead: 'Yield > 4% on the basket → cap rates have widened, distressed-buyer environment. Yield < 2.5% → cap rates compressed, defensive positioning.',
    methodology: 'Equal-weighted trailing-12-month dividend yield of the basket. Yahoo Finance dividend and price feed.',
  },
  {
    id: 'REIT_YIELD_SPREAD_10Y',
    source: 'derived',
    category: 'industrial-re',
    label: 'REIT Yield − 10Y Treasury (Spread)',
    shortLabel: 'REIT Spread',
    unit: 'bps', decimals: 0, freq: 'daily', transform: 'level',
    release: 'Daily',
    direction: 'higher_better',
    longTermNormYears: 10,
    composite: { dependsOn: ['REIT_AVG_DIV_YIELD', 'DGS10'], compute: 'spread_bps' },
    whyMatters: 'Risk premium over the risk-free rate. Historically averages ~150-300bps. Negative spreads (REIT yield below Treasuries) are unusual and signal bubble conditions.',
    howToRead: '> 400bps → distressed/cheap industrial real-estate-equity environment. 150-300bps → normal. < 100bps → expensive, late-cycle.',
    methodology: 'REIT_AVG_DIV_YIELD × 100 − DGS10 × 100 (spread in basis points).',
  },
  {
    id: 'MFG_CAPACITY_UTIL',
    source: 'fred', sourceId: 'MCUMFN',
    category: 'industrial-re',
    label: 'Manufacturing Capacity Utilization',
    shortLabel: 'Mfg Cap Util',
    unit: '%', decimals: 1, freq: 'monthly', transform: 'level',
    release: 'Federal Reserve G.17, ~mid-month',
    direction: 'higher_better',
    longTermNormYears: 10,
    whyMatters: 'Manufacturing capacity utilization correlates with industrial-RE demand because high utilization signals tight production capacity, often resolved with new facilities. > 80% has historically marked sustained industrial construction cycles.',
    howToRead: 'Above 78% sustained → expect industrial construction to remain elevated. Below 75% → industrial construction decelerates 2-3Q later.',
    methodology: 'Federal Reserve G.17 Industrial Production and Capacity Utilization. Manufacturing (NAICS) only (MCUMFN), as % of capacity.',
  },
  {
    id: 'DGS10',
    source: 'fred', sourceId: 'DGS10',
    category: 'industrial-re',
    label: '10Y Treasury Yield',
    shortLabel: '10Y Treasury',
    unit: '%', decimals: 2, freq: 'daily', transform: 'level',
    release: 'Federal Reserve, daily',
    direction: 'neutral',
    longTermNormYears: 10,
    whyMatters: '10Y Treasury yield is the cap-rate floor for REIT pricing. Industrial REIT yield-spread compresses when 10Y rallies and widens when 10Y sells off. Used as the discount-rate baseline for industrial real estate valuation.',
    howToRead: 'Compare REIT basket dividend yield vs DGS10. Spread > 300bps is wide / cheap REIT environment. Spread < 100bps is tight / expensive.',
    methodology: 'Federal Reserve constant-maturity 10-year Treasury yield, daily.',
  },

  // ============================================================================
  // MIDDLE MILE — long-haul freight, line-haul, intermodal
  // ============================================================================
  {
    id: 'DIESEL_RETAIL',
    source: 'eia', sourceId: 'DIESEL_RETAIL',
    category: 'middle-mile',
    label: 'Diesel Retail Price (US Avg)',
    shortLabel: 'Diesel',
    unit: '$/gal', decimals: 3, freq: 'weekly', transform: 'level',
    release: 'EIA Weekly Petroleum Status, every Monday',
    direction: 'lower_better',
    longTermNormYears: 10,
    featured: true,
    whyMatters: 'Diesel is roughly 25-30% of total operating cost for a long-haul carrier and the largest single variable input. Spot-rate carriers absorb diesel moves directly because their rates settle per-load; contract-rate carriers have a fuel surcharge that lags the DOE national average by 60-90 days, so a sharp diesel move pressures contract carrier margins for a quarter before being passed through. Retail diesel also flows to last-mile delivery costs, particularly for regional parcel and LTL operators.',
    howToRead: 'Above 10y norm and rising → carrier margin pressure; expect contract-rate increases in the 60-90 day window and tighter capacity as smaller fleets pull trucks. Above norm and falling → margins recovering, capacity stable. Below norm and falling → shipper-favorable; spot rates soften, RFP season becomes buyer-friendly. Below norm and rising → watch for the inflection.',
    methodology: 'EIA Weekly Retail On-Highway Diesel Prices, US national average across all grades. Updated every Monday at the close of the prior week.',
  },
  {
    id: 'GASOLINE_RETAIL',
    source: 'eia', sourceId: 'GASOLINE_RETAIL',
    category: 'middle-mile',
    label: 'Gasoline Retail Price (US Avg)',
    shortLabel: 'Gasoline',
    unit: '$/gal', decimals: 3, freq: 'weekly', transform: 'level',
    release: 'EIA Weekly Petroleum Status, every Monday',
    direction: 'lower_better',
    longTermNormYears: 10,
    whyMatters: 'Less direct than diesel for trucking but matters for last-mile gasoline-fueled delivery vans, courier networks, and consumer freight elasticity. Gasoline moves with WTI on a faster timeline than diesel because of refining-margin dynamics.',
    howToRead: 'Diesel-gasoline spread > $0.50/gal → diesel demand outrunning gasoline (commercial activity strong). < $0.20 → gasoline tight (consumer-side demand or refinery dynamics). Track the spread, not just levels.',
    methodology: 'EIA Weekly Retail Gasoline Price, US average across all grades.',
  },
  {
    id: 'CASS_SHIPMENTS',
    source: 'scrape:cass',
    category: 'middle-mile',
    label: 'Cass Freight Index — Shipments',
    shortLabel: 'Cass Shipments',
    unit: '', decimals: 1, freq: 'monthly', transform: 'level',
    release: 'Cass Information Systems, ~12th of month',
    direction: 'higher_better',
    longTermNormYears: 10,
    featured: true,
    whyMatters: 'The single most-watched freight-volume index in North America. Cass processes ~$44B of freight bills annually and reports an aggregate shipment count index. Tracks the broad demand pulse for trucking — both contract and spot, both LTL and TL — earlier than any government series. Volume inflections lead Class 8 truck orders by 2-3 months.',
    howToRead: 'YoY growth > +3% sustained → demand expansion, capacity tight, spot rates rising. Range −2% to +3% → balanced. < −5% sustained → freight recession, capacity exits, expect spot-rate floor in 1-2Q.',
    methodology: 'Cass Information Systems Freight Index. Shipment-count component, indexed (Jan 1990 = 1.00). Released monthly.',
  },
  {
    id: 'CASS_EXPENDITURES',
    source: 'scrape:cass',
    category: 'middle-mile',
    label: 'Cass Freight Index — Expenditures',
    shortLabel: 'Cass Expend.',
    unit: '', decimals: 1, freq: 'monthly', transform: 'level',
    release: 'Cass Information Systems, ~12th of month',
    direction: 'neutral',
    longTermNormYears: 10,
    whyMatters: 'Total dollars spent on freight — Cass\'s shipments × rate × fuel. Diverges from the shipments index when rates or fuel move. The shipments-expenditures spread is one of the cleanest reads on freight rate inflation.',
    howToRead: 'Expenditures rising while shipments flat → rate inflation. Expenditures falling while shipments rising → rate deflation. The two converge at every cycle inflection.',
    methodology: 'Cass Information Systems Freight Index, Expenditures component (Jan 1990 = 1.00).',
  },
  {
    id: 'CASS_LINEHAUL',
    source: 'scrape:cass',
    category: 'middle-mile',
    label: 'Cass Truckload Linehaul Index',
    shortLabel: 'Cass Linehaul',
    unit: '', decimals: 1, freq: 'monthly', transform: 'level',
    release: 'Cass Information Systems, ~12th of month',
    direction: 'neutral',
    longTermNormYears: 10,
    whyMatters: 'Pure linehaul rates ex-fuel — strips out the fuel-surcharge noise from the headline expenditures index. Cleanest read on what carriers are getting paid for the trucking work itself.',
    howToRead: 'Linehaul YoY > +5% → tight capacity, carriers pricing through. Linehaul YoY < −3% → freight recession, shipper-favorable RFP season.',
    methodology: 'Cass Truckload Linehaul Index. Excludes fuel and accessorial charges (Jan 2005 = 1.00).',
  },
  {
    id: 'ATA_TONNAGE',
    source: 'fred', sourceId: 'TRUCKD11',
    category: 'middle-mile',
    label: 'ATA Truck Tonnage Index',
    shortLabel: 'ATA Tonnage',
    unit: '', decimals: 1, freq: 'monthly', transform: 'level',
    release: 'American Trucking Associations, ~3 weeks after month-end',
    direction: 'higher_better',
    featured: true,
    longTermNormYears: 10,
    whyMatters: 'ATA\'s tonnage index measures volume hauled by ATA member fleets (mostly contract carriers). Confirms or contradicts the Cass shipments signal. Divergence between Cass (broader, includes spot) and ATA (contract-tilted) tells you whether spot or contract is leading the cycle.',
    howToRead: 'ATA up + Cass up → broad expansion. ATA up + Cass down → contract-favorable, spot weak (e.g., 2024 mid-cycle). ATA down + Cass up → spot leading recovery.',
    methodology: 'ATA Truck Tonnage Index. Seasonally adjusted, indexed to 2015=100.',
  },  {
    id: 'TRUCKING_EMP',
    source: 'fred', sourceId: 'CES4348400001',
    category: 'middle-mile',
    label: 'Truck Transportation Employment',
    shortLabel: 'Trucking Emp',
    unit: 'k', decimals: 0, freq: 'monthly', transform: 'level',
    release: 'BLS CES, ~1st Friday',
    direction: 'higher_better',
    longTermNormYears: 10,
    whyMatters: 'Headcount in NAICS 484. The cleanest read on capacity in trucking — when employment falls capacity exits, when it rises capacity enters. Lags rate moves by 2-3 quarters.',
    howToRead: 'Falling employment + falling rates → capacity flushing out (look for spot-rate floor). Falling employment + rising rates → tight capacity. Rising employment + rising rates → balanced expansion.',
    methodology: 'BLS CES4348100001 — All Employees, Truck Transportation. Seasonally adjusted.',
  },
  {
    id: 'AAR_CARLOADS',
    source: 'fred', sourceId: 'RAILFRTCARLOADS',
    category: 'middle-mile',
    label: 'Rail Freight Carloads',
    shortLabel: 'Rail Carloads',
    unit: '', decimals: 1, freq: 'monthly', transform: 'level',
    release: 'AAR via FRED, monthly',
    direction: 'higher_better',
    longTermNormYears: 10,
    whyMatters: 'Total US rail carloads weekly — the highest-frequency goods-movement series available. Rail carries grain, coal, chemicals, and intermodal containers. Carloads are sensitive to industrial activity and energy demand; intermodal is sensitive to imports and trucking economics.',
    howToRead: 'YoY > +3% → industrial activity expanding. < −3% → contracting. Compare to intermodal (next series) to disambiguate domestic-industrial vs import-driven moves.',
    methodology: 'AAR (Association of American Railroads) Weekly Rail Traffic. Total carloads, all commodities, US Class I railroads. In thousands of cars.',
  },
  {
    id: 'AAR_INTERMODAL',
    source: 'fred', sourceId: 'RAILFRTINTERMODAL',
    category: 'middle-mile',
    label: 'Rail Freight Intermodal Traffic',
    shortLabel: 'Intermodal',
    unit: '', decimals: 1, freq: 'monthly', transform: 'level',
    release: 'AAR via FRED, monthly',
    direction: 'higher_better',
    longTermNormYears: 10,
    featured: true,
    whyMatters: 'Containers and trailers on flatcars. The most direct indicator of import-driven freight flowing inland from West Coast ports. Leads Cass shipments by 1-2 weeks for goods-import cycles.',
    howToRead: 'Intermodal up + carloads up → broad freight strength. Intermodal up + carloads flat → import-led recovery. Intermodal down → import softness, watch container freight rates and port volumes.',
    methodology: 'AAR Weekly Rail Traffic. Intermodal units (containers + trailers), Class I railroads. In thousands.',
  },
  {
    id: 'TSI_FREIGHT',
    source: 'fred', sourceId: 'TSIFRGHT',
    category: 'middle-mile',
    label: 'Transportation Services Index — Freight',
    shortLabel: 'TSI Freight',
    unit: '', decimals: 1, freq: 'monthly', transform: 'level',
    release: 'BTS, ~6 weeks after month-end',
    direction: 'higher_better',
    longTermNormYears: 10,
    whyMatters: 'BTS-aggregated freight ton-miles across truck, rail, water, pipeline, and air. Most comprehensive single goods-movement number, but lagged ~6 weeks. Use as the validation cross-check on the higher-frequency Cass and AAR signals.',
    howToRead: 'TSI accelerating + Cass accelerating → real broad expansion confirmed. TSI lagging Cass turn → wait for confirmation before allocating capital.',
    methodology: 'BTS Transportation Services Index, freight component. Monthly index (2000=100), seasonally adjusted.',
  },
  {
    id: 'HEAVY_TRUCK_SAAR',
    source: 'fred', sourceId: 'HTRUCKSSAAR',
    category: 'middle-mile',
    label: 'Heavy Truck Sales SAAR',
    shortLabel: 'Class 8 Sales',
    unit: 'k', decimals: 0, freq: 'monthly', transform: 'level',
    release: 'BEA, monthly',
    direction: 'higher_better',
    longTermNormYears: 10,
    whyMatters: 'Class 8 truck sales (the over-the-road tractors). Strong cyclical signal — fleets buy when demand is rising and capacity is tight. Sales above 500K SAAR have historically marked overheating; below 250K marks freight recessions.',
    howToRead: '> 500K SAAR → late-cycle, capacity expansion peaking. 350-500K → balanced. < 250K → freight recession, capacity exit.',
    methodology: 'BEA Heavy Weight Truck Sales, seasonally adjusted annual rate, in thousands of units.',
  },  {
    id: 'PPI_LONGHAUL_TL',
    source: 'fred', sourceId: 'PCU484121484121',
    category: 'middle-mile',
    label: 'PPI: Long-Distance General Freight TL',
    shortLabel: 'TL PPI',
    unit: '', decimals: 1, freq: 'monthly', transform: 'level',
    release: 'BLS PPI, mid-month',
    direction: 'neutral',
    longTermNormYears: 10,
    whyMatters: 'Government-published PPI for long-haul truckload — captures contract rates more than spot. Lags Cass linehaul by 1-2 months. Useful as a confirmation of the spot-rate signal flowing through to contract.',
    howToRead: 'TL PPI YoY > Cass linehaul YoY → contract catching up to spot, late-cycle. TL PPI YoY < Cass linehaul YoY → spot pulling away, early-cycle.',
    methodology: 'BLS PPI series PCU484121484121 — General Freight Trucking, Long-Distance Truckload.',
  },

  // ============================================================================
  // LAST MILE — local delivery, courier, urban
  // ============================================================================
  {
    id: 'COURIER_EMP',
    source: 'fred', sourceId: 'CES4349200001',
    category: 'last-mile',
    label: 'Couriers & Messengers Employment',
    shortLabel: 'Courier Emp',
    unit: 'k', decimals: 0, freq: 'monthly', transform: 'level',
    release: 'BLS CES, ~1st Friday',
    direction: 'higher_better',
    longTermNormYears: 10,
    featured: true,
    whyMatters: 'NAICS 4922 — couriers and messengers. UPS, FedEx Ground, regional parcel, and gig couriers. Most direct read on parcel-delivery capacity. Headcount tripled from ~700K to over 1.1M between 2015 and 2022 as e-commerce penetration accelerated.',
    howToRead: 'Headcount rising + e-commerce share rising → demand-led expansion. Headcount falling while e-commerce flat → margin pressure, automation absorption (locker boxes, drone pilots).',
    methodology: 'BLS CES4349200001 — All Employees, Couriers and Messengers. Seasonally adjusted.',
  },
  {
    id: 'TRANSPORT_SUPPORT_EMP',
    source: 'fred', sourceId: 'CES4348800001',
    category: 'last-mile',
    label: 'Support Activities for Transportation Emp',
    shortLabel: 'Transp Support',
    unit: 'k', decimals: 0, freq: 'monthly', transform: 'level',
    release: 'BLS CES, ~1st Friday',
    direction: 'higher_better',
    longTermNormYears: 10,
    whyMatters: 'Support-activities employment captures crossdock workers, last-mile coordinators, drayage operators, and similar roles that wrap around the truck transportation industry. Useful complement to direct courier and trucking employment.',
    howToRead: 'Use alongside courier employment for full last-mile labor picture. Divergence (courier up, support flat) → e-commerce-only growth. Both up → broad goods-movement strength.',
    methodology: 'BLS CES4348800001 — All Employees, Support Activities for Transportation. Seasonally adjusted.',
  },
  {
    id: 'USPS_FIRST_CLASS',
    source: 'scrape:usps',
    category: 'last-mile',
    label: 'USPS First-Class Mail Volume',
    shortLabel: 'USPS 1st Class',
    unit: 'M pieces', decimals: 0, freq: 'quarterly', transform: 'level',
    release: 'USPS Quarterly RPW Report',
    direction: 'neutral',
    longTermNormYears: 10,
    whyMatters: 'First-class mail has been in secular decline (~5% per year) for two decades. Useful baseline for measuring the structural shift to digital. Tracks trends in physical bills and personal correspondence.',
    howToRead: 'Decline rate steepening = digital substitution accelerating. Decline rate easing = digital saturation reached.',
    methodology: 'USPS Revenue, Pieces, and Weight (RPW) Report, First-Class Mail volume in millions of pieces.',
  },
  {
    id: 'USPS_PACKAGES',
    source: 'scrape:usps',
    category: 'last-mile',
    label: 'USPS Package Services Volume',
    shortLabel: 'USPS Packages',
    unit: 'M pieces', decimals: 0, freq: 'quarterly', transform: 'level',
    release: 'USPS Quarterly RPW Report',
    direction: 'higher_better',
    longTermNormYears: 10,
    whyMatters: 'USPS package volume — Priority Mail, Parcel Select, last-mile delivery for Amazon and others. Direct read on USPS\'s share of e-commerce delivery; rising volume suggests USPS is winning last-mile economic competition with FedEx/UPS.',
    howToRead: 'Compare YoY growth rate against total e-commerce growth. USPS outpacing → share gain. USPS lagging → share loss to private carriers.',
    methodology: 'USPS Revenue, Pieces, and Weight (RPW) Report, Package Services in millions of pieces.',
  },
  {
    id: 'ECOM_SHARE',
    source: 'fred', sourceId: 'ECOMPCTSA',
    category: 'last-mile',
    label: 'E-commerce % of Retail Sales',
    shortLabel: 'E-com Share',
    unit: '%', decimals: 1, freq: 'quarterly', transform: 'level',
    release: 'Census, ~7 weeks after quarter-end',
    direction: 'higher_better',
    longTermNormYears: 10,
    featured: true,
    whyMatters: 'The single number for the structural last-mile demand thesis. Pre-COVID trend: ~+1pp/year. COVID shock: 11%→16% in two quarters. Post-shock: drift back to trend at 15-16%. Each 1pp of share = ~$50B of e-commerce sales = millions of additional last-mile parcels per day.',
    howToRead: 'Share above trend (~17% as of 2026) → over-shoot, normalization risk for last-mile capacity. Share at trend → secular tailwind intact. Share below trend → cyclical weakness or e-commerce maturity.',
    methodology: 'Census ECOMPCTSA — E-commerce retail sales as percent of total retail sales, seasonally adjusted.',
  },
  {
    id: 'ECOM_SALES',
    source: 'fred', sourceId: 'ECOMSA',
    category: 'last-mile',
    label: 'E-commerce Retail Sales',
    shortLabel: 'E-com Sales',
    unit: '$M', decimals: 0, freq: 'quarterly', transform: 'level',
    release: 'Census, ~7 weeks after quarter-end',
    direction: 'higher_better',
    longTermNormYears: 10,
    whyMatters: 'Dollar volume of e-commerce. Multiplied by an average parcel-per-order ratio, gives ballpark parcel-volume needs for the last-mile network.',
    howToRead: 'YoY growth > 8% → expansion period. < 5% → maturation phase. Track quarter-over-quarter for cyclical reads.',
    methodology: 'Census ECOMSA — E-commerce retail sales, seasonally adjusted, millions of dollars.',
  },
  {
    id: 'RETAIL_EMP',
    source: 'fred', sourceId: 'CEU4200000001',
    category: 'last-mile',
    label: 'Retail Trade Employment',
    shortLabel: 'Retail Emp',
    unit: 'k', decimals: 0, freq: 'monthly', transform: 'level',
    release: 'BLS CES, ~1st Friday',
    direction: 'neutral',
    longTermNormYears: 10,
    whyMatters: 'Retail employment is in secular contraction as e-commerce displaces physical retail. Useful comparison to courier employment — the two should track inversely as fulfillment moves from store to DC.',
    howToRead: 'Retail emp falling + courier emp rising → ongoing e-commerce shift. Both falling → consumer weakness. Retail emp rising → either physical-retail revival or new format growth.',
    methodology: 'BLS CEU4200000001 — All Employees, Retail Trade. Seasonally adjusted.',
  },
  {
    id: 'LIGHT_TRUCK_SAAR',
    source: 'fred', sourceId: 'LTRUCKSA',
    category: 'last-mile',
    label: 'Light Trucks SAAR',
    shortLabel: 'Light Truck Sales',
    unit: 'k', decimals: 0, freq: 'monthly', transform: 'level',
    release: 'BEA, monthly',
    direction: 'neutral',
    featured: true,
    longTermNormYears: 10,
    whyMatters: 'Light-truck sales include the delivery vans (Sprinter, Transit, ProMaster) that power last-mile fleets. While not isolating commercial-only, the series captures the broader vehicle availability for last-mile capacity expansion.',
    howToRead: 'Surge in light-truck SAAR alongside rising courier emp → fleet capacity expansion. Falling sales + falling employment → last-mile capacity contraction.',
    methodology: 'BEA Light Weight Trucks Sales, SAAR, thousands of units.',
  },
  {
    id: 'GASREG',
    source: 'fred', sourceId: 'GASREGW',
    category: 'last-mile',
    label: 'Retail Gasoline Price (Regular)',
    shortLabel: 'Gas Price',
    unit: '$/gal', decimals: 3, freq: 'weekly', transform: 'level',
    release: 'EIA Weekly Petroleum Status, every Monday',
    direction: 'lower_better',
    featured: true,
    longTermNormYears: 10,
    whyMatters: 'Last-mile delivery fleets — mostly gas-fueled vans and pickup trucks — have direct exposure. Each $0.50/gal move equates to roughly 1.5-2pp on last-mile fuel cost as % of revenue.',
    howToRead: 'Spike sustained > 30 days → expect last-mile carriers to add fuel surcharges. Decline > 30 days → margin tailwind.',
    methodology: 'EIA US average regular all-formulations gasoline price, weekly retail.',
  },
  {
    id: 'PPI_COURIERS',
    source: 'fred', sourceId: 'PCU492492',
    category: 'last-mile',
    label: 'PPI: Couriers & Messengers',
    shortLabel: 'Courier PPI',
    unit: '', decimals: 1, freq: 'monthly', transform: 'level',
    release: 'BLS PPI, mid-month',
    direction: 'lower_better',
    longTermNormYears: 10,
    whyMatters: 'Government-published price index for parcel-delivery services. Lagging measure but the cleanest aggregate read on courier rate inflation. UPS / FedEx general rate increases (GRIs) flow through this series.',
    howToRead: 'Trending up while diesel and labor are easing → carriers pushing margin via GRIs. Trending up alongside input inflation → pass-through environment.',
    methodology: 'BLS PPI series PCU492492 — Couriers and Messengers.',
  },
  {
    id: 'PPI_LOCAL_TRUCKING',
    source: 'fred', sourceId: 'PCU484110484110',
    category: 'last-mile',
    label: 'PPI: General Freight Trucking, Local',
    shortLabel: 'Local Truck PPI',
    unit: '', decimals: 1, freq: 'monthly', transform: 'level',
    release: 'BLS PPI, mid-month',
    direction: 'lower_better',
    longTermNormYears: 10,
    whyMatters: 'Local-trucking rate inflation. Captures regional LTL and dedicated-local rates. Useful for foodservice distributors and regional 3PLs.',
    howToRead: 'Track alongside long-haul TL PPI; sustained gap (local out-pacing) signals labor-cost pressure concentrated in urban markets.',
    methodology: 'BLS PPI series PCU484110484110 — General Freight Trucking, Local.',
  },

  // ============================================================================
  // INTERNATIONAL / SOURCING — global ocean, air, ports
  // ============================================================================
  {
    id: 'GSCPI',
    source: 'scrape:nyfed-gscpi',
    category: 'international',
    label: 'NY Fed Global Supply Chain Pressure Index',
    shortLabel: 'GSCPI',
    unit: 'σ', decimals: 2, freq: 'monthly', transform: 'level',
    release: 'NY Fed, ~5th of month',
    direction: 'lower_better',
    longTermNormYears: 25,
    featured: true,
    whyMatters: 'NY Fed\'s standardized composite of global transportation costs and PMI delivery-time pressures. Standard-deviations from average — zero is normal, positive is pressure (tight, slow), negative is loose. The 2021-22 peak of +4.3σ was the most extreme reading in the series\' history. Gold-standard single-number for international supply-chain stress.',
    howToRead: '> +1σ → meaningful global stress, expect rate increases on key lanes. < −1σ → loose system, shipper-favorable. The sign matters more than the level.',
    methodology: 'NY Fed Global Supply Chain Pressure Index. Composite of Baltic Dry, Harpex, BLS air-freight cost indices, plus PMI subcomponents (delivery times, backlogs, purchased stocks) for Eurozone, China, Japan, South Korea, Taiwan, UK, US. Standardized to mean 0, sd 1 over the full sample.',
  },  {
    id: 'FBX_GLOBAL',
    source: 'scrape:freightos',
    category: 'international',
    label: 'Freightos Baltic Index — Global',
    shortLabel: 'FBX Global',
    unit: '$/40ft', decimals: 0, freq: 'daily', transform: 'level',
    release: 'Freightos / Baltic Exchange, daily',
    direction: 'lower_better',
    longTermNormYears: 5,
    whyMatters: 'Daily container rate index from Freightos in partnership with the Baltic Exchange. Higher-frequency than WCI; useful for catching mid-week rate inflections.',
    howToRead: 'Cross-reference with WCI on Thursdays. FBX leading WCI direction = real-time rate confirmation.',
    methodology: 'Freightos Baltic Index, global composite. 12 trade lanes weighted by trade volume.',
  },  {
    id: 'BUNKER_VLSFO_SIN',
    source: 'scrape:shipbunker',
    category: 'international',
    label: 'VLSFO Bunker — Singapore',
    shortLabel: 'VLSFO SIN',
    unit: '$/mt', decimals: 1, freq: 'daily', transform: 'level',
    release: 'Ship & Bunker, daily',
    direction: 'lower_better',
    longTermNormYears: 5,
    whyMatters: 'Very Low Sulfur Fuel Oil — the standard bunker fuel since IMO 2020 sulfur cap. Bunker is 30-50% of voyage cost for container ships, so VLSFO moves directly drive freight rate floors. Singapore is the world\'s largest bunker port.',
    howToRead: 'VLSFO rising sharply → expect carriers to pass through via emergency bunker surcharges within 30 days. Falling → fuel-cost tailwind, downward pressure on container rates.',
    methodology: 'Ship & Bunker, Singapore VLSFO daily price in USD per metric tonne.',
  },
  {
    id: 'BUNKER_VLSFO_RTM',
    source: 'scrape:shipbunker',
    category: 'international',
    label: 'VLSFO Bunker — Rotterdam',
    shortLabel: 'VLSFO RTM',
    unit: '$/mt', decimals: 1, freq: 'daily', transform: 'level',
    release: 'Ship & Bunker, daily',
    direction: 'lower_better',
    longTermNormYears: 5,
    whyMatters: 'European-side bunker fuel benchmark. Spread vs Singapore signals regional demand and refining-margin dynamics.',
    howToRead: 'RTM-Singapore spread > $30/mt → European refining tight. Compare to crude-oil location spreads.',
    methodology: 'Ship & Bunker, Rotterdam VLSFO daily price in USD per metric tonne.',
  },
  {
    id: 'US_IMPORTS',
    source: 'fred', sourceId: 'BOPGIMP',
    category: 'international',
    label: 'US Imports of Goods',
    shortLabel: 'US Imports',
    unit: '$M', decimals: 0, freq: 'monthly', transform: 'level',
    release: 'BEA / Census FT900, ~6 weeks after month-end',
    direction: 'neutral',
    longTermNormYears: 10,
    whyMatters: 'Total US goods imports. The aggregate demand pulse for the international supply chain. YoY growth above 5% has historically marked import-led inventory builds; sustained negative YoY signals demand contraction.',
    howToRead: 'YoY > +5% sustained + container rates rising → real demand-led tightness. YoY > +5% + container rates flat → capacity catching up. YoY negative → importer destocking.',
    methodology: 'BEA / Census FT900 trade balance. Total goods imports, seasonally adjusted, in millions of dollars. FRED series IR.',
  },
  {
    id: 'US_EXPORTS',
    source: 'fred', sourceId: 'BOPGEXP',
    category: 'international',
    label: 'US Exports of Goods',
    shortLabel: 'US Exports',
    unit: '$M', decimals: 0, freq: 'monthly', transform: 'level',
    release: 'BEA / Census FT900, ~6 weeks after month-end',
    direction: 'higher_better',
    longTermNormYears: 10,
    whyMatters: 'US goods exports. Important for containerized export flows (agricultural, plastics, scrap), and for understanding bilateral trade-deficit dynamics that can drive container repositioning costs.',
    howToRead: 'Use as cross-check on imports — container imbalance drives repositioning costs and "slot" availability for US shippers.',
    methodology: 'BEA / Census FT900 trade balance. Total goods exports, seasonally adjusted, millions of dollars.',
  },
  {
    id: 'TWD_BROAD',
    source: 'fred', sourceId: 'DTWEXBGS',
    category: 'international',
    label: 'USD Trade-Weighted Index (Broad)',
    shortLabel: 'TWD Broad',
    unit: '', decimals: 1, freq: 'daily', transform: 'level',
    release: 'Federal Reserve, daily',
    direction: 'neutral',
    longTermNormYears: 10,
    whyMatters: 'The dollar against a trade-weighted basket. Stronger dollar → cheaper imports, higher import volumes; weaker dollar → headwind for importers. Pass-through to landed cost is rapid (1-2 months) for non-hedged commodity inputs.',
    howToRead: 'Sustained strengthening (>5% in 6mo) → expect import-volume tailwind. Weakening → headwind, watch for import compression.',
    methodology: 'Federal Reserve Trade Weighted US Dollar Index: Broad, Goods and Services. Daily.',
  },
  {
    id: 'PORT_LA_TEU',
    source: 'scrape:imf-portwatch',
    sourceId: 'port664-imports',
    category: 'international',
    label: 'LA-Long Beach - Container Imports (TEU)',
    shortLabel: 'LA-LB Imports',
    unit: 'TEU', decimals: 0, freq: 'monthly', transform: 'level',
    release: 'IMF PortWatch, daily (monthly aggregate)',
    direction: 'higher_better',
    longTermNormYears: 5,
    featured: true,
    whyMatters: 'IMF PortWatch combines San Pedro Bay (LA + Long Beach) into a single port complex - together about 40% of US containerized imports. Cleanest single signal for trans-Pacific inbound volumes, available daily and aggregated monthly.',
    howToRead: 'Sustained > 10M TEU-equivalent/month means tight; expect West Coast rail congestion. < 7M means soft, possibly East Coast routing taking share.',
    methodology: 'IMF PortWatch Daily_Ports_Data, port664 (Los Angeles-Long Beach), import_container summed by month. Uses AIS vessel data + ship deadweight + payload utilization estimates.',
  },
  {
    id: 'PORT_LB_TEU',
    source: 'scrape:imf-portwatch',
    sourceId: 'port664-calls',
    category: 'international',
    label: 'LA-Long Beach - Container Ship Calls',
    shortLabel: 'LA-LB Ship Calls',
    unit: 'ships', decimals: 0, freq: 'monthly', transform: 'level',
    release: 'IMF PortWatch, daily (monthly aggregate)',
    direction: 'higher_better',
    longTermNormYears: 5,
    whyMatters: 'Number of container vessels arriving at the LA-LB complex per month. A complementary view to volume (PORT_LA_TEU): rising volume + falling calls = larger ships / fewer trips (efficiency); falling volume + steady calls = under-utilization.',
    howToRead: 'Calls rising while volume falling means over-capacity (rate pressure down). Calls flat while volume rising means up-sized vessels.',
    methodology: 'IMF PortWatch Daily_Ports_Data, port664, portcalls_container summed by month.',
  },
  {
    id: 'PORT_NYNJ_TEU',
    source: 'scrape:imf-portwatch',
    sourceId: 'port815-imports',
    category: 'international',
    label: 'NY-NJ - Container Imports (TEU)',
    shortLabel: 'NY-NJ Imports',
    unit: 'TEU', decimals: 0, freq: 'monthly', transform: 'level',
    release: 'IMF PortWatch, daily (monthly aggregate)',
    direction: 'higher_better',
    longTermNormYears: 5,
    whyMatters: 'Largest US East Coast container port. Volume here vs LA-LB indicates East-vs-West routing dynamics - Suez routing, Panama Canal water levels, all affect this split.',
    howToRead: 'NY/NJ outpacing LA-LB means East-shift in routing (Suez accessible, Panama deep). LA-LB outpacing means West-favorable.',
    methodology: 'IMF PortWatch Daily_Ports_Data, port815 (New York-New Jersey), import_container summed by month.',
  },
  {
    id: 'AIR_TRANSP_EMP',
    source: 'fred', sourceId: 'CES4348100001',
    category: 'international',
    label: 'Air Transportation Employment',
    shortLabel: 'Air Transp Emp',
    unit: 'k', decimals: 0, freq: 'monthly', transform: 'level',
    release: 'BLS CES, ~1st Friday',
    direction: 'higher_better',
    longTermNormYears: 10,
    whyMatters: 'Headcount in air transportation. Proxy for activity in air-cargo and passenger-belly capacity. Used as a substitute for the more direct (but unavailable on FRED at high frequency) air-freight tonne-km series.',
    howToRead: 'Rising employment + rising imports → air capacity scaling with goods-movement demand. Compare with international port volumes; rising sharply when ocean rates spike signals modal shift to air for time-sensitive freight.',
    methodology: 'BLS CES4348100001 — All Employees, Air Transportation. Seasonally adjusted.',
  },

  // ============================================================================
  // COMPOSITE — Supply Chain Pressure (top of overview)
  // ============================================================================
  {
    id: 'SCP_COMPOSITE',
    source: 'derived',
    category: 'composite',
    label: 'Supply Chain Pressure Composite',
    shortLabel: 'SC Pressure',
    unit: 'σ', decimals: 2, freq: 'monthly', transform: 'level',
    release: 'Computed at refresh',
    direction: 'lower_better',
    longTermNormYears: 10,
    featured: true,
    composite: {
      dependsOn: ['GSCPI', 'CASS_SHIPMENTS', 'DIESEL_RETAIL', 'FBX_GLOBAL', 'BUNKER_VLSFO_SIN'],
      compute: 'scp_zscore_blend',
    },
    whyMatters: 'Single-number summary of system-wide supply-chain stress. Averages five z-scores: GSCPI (direct), Cass Shipments (inverted — lower volume = looser), Diesel deviation from 10y norm, Freightos Baltic Index (FBX), and Singapore bunker fuel. Designed to give an instant "is the system tight or loose" read.',
    howToRead: 'Above +1σ → meaningful stress, plan for higher costs across modes. Above +2σ → severe (matches 2021-22 peak conditions). Below −1σ → loose system, plan for shipper-favorable conditions and possibly capacity rationalization at carriers.',
    methodology: 'Equal-weighted average of: z-score of GSCPI (10y window), inverse z-score of CASS_SHIPMENTS (10y), z-score of DIESEL_RETAIL deviation from its 10y mean, z-score of FBX_GLOBAL (5y window), z-score of BUNKER_VLSFO_SIN (5y window). Each component standardized to mean 0, sd 1 over its window. Recomputed at every refresh.',
  },

  // ============================================================================
  // V2 NEW METRICS — added 2026-04-26
  // ============================================================================

  // ---- DC: Manufacturing PMI delivery times (regional Fed surveys) ----
  {
    id: 'EMPIRE_DELIVERY',
    source: 'fred', sourceId: 'DTCDISA066MSFRBNY',
    category: 'dc',
    label: 'Empire State Mfg Delivery Time',
    shortLabel: 'NY Delivery',
    unit: '', decimals: 1, freq: 'monthly', transform: 'level',
    release: 'NY Fed Empire State Mfg Survey, ~mid-month',
    direction: 'higher_better',
    longTermNormYears: 10,
    whyMatters: 'NY Fed regional manufacturing survey subindex measuring whether suppliers are delivering faster (negative diffusion = faster) or slower (positive = slower / supply-chain stress). The closest free public substitute for ISM Manufacturing Suppliers Deliveries Index, which left FRED in 2021. Positive readings sustained for multiple months historically mark periods of supply-chain pressure (2021-22 peak hit +30); negative readings indicate slack and capacity availability.',
    howToRead: 'Above +10 means supply-chain pressure intensifying; expect lead-time inflation. Around 0 is balanced. Below -5 means slack, supplier-favorable. Watch the 3-month change more than the level.',
    methodology: 'NY Fed Empire State Manufacturing Survey, Current Delivery Time Diffusion Index, seasonally adjusted (DTCDISA066MSFRBNY).',
  },
  {
    id: 'PHILLY_DELIVERY',
    source: 'fred', sourceId: 'DTCDFSA066MSFRBPHI',
    category: 'dc',
    label: 'Philly Fed Mfg Delivery Time',
    shortLabel: 'Philly Delivery',
    unit: '', decimals: 1, freq: 'monthly', transform: 'level',
    release: 'Philly Fed Manufacturing Survey, 3rd Thursday',
    direction: 'higher_better',
    longTermNormYears: 10,
    whyMatters: 'Philadelphia Fed regional manufacturing survey delivery-time subindex. Cross-validates Empire State (NY) - when both regions move the same direction, the signal is reliable. Diverging readings flag region-specific dynamics.',
    howToRead: 'Compare with Empire State: aligned moves are real broad signal. Divergence is regional noise. Above +5 sustained means supply-chain pressure.',
    methodology: 'Philadelphia Fed Manufacturing Business Outlook Survey, Current Delivery Time Diffusion Index (DTCDFSA066MSFRBPHI).',
  },
  {
    id: 'DALLAS_DELIVERY',
    source: 'fred', sourceId: 'DTMSAMFRBDAL',
    category: 'dc',
    label: 'Dallas Fed Mfg Delivery Time',
    shortLabel: 'Dallas Delivery',
    unit: '', decimals: 1, freq: 'monthly', transform: 'level',
    release: 'Dallas Fed Manufacturing Survey, last Monday',
    direction: 'higher_better',
    longTermNormYears: 10,
    whyMatters: 'Dallas Fed Texas Manufacturing Outlook Survey delivery-time subindex. Texas is the leading destination for nearshoring and reshoring (semiconductors, EV batteries, defense, energy equipment), so this region is a leading indicator of South-region supply chain capacity.',
    howToRead: 'Use alongside Empire State and Philly to triangulate the manufacturing PMI delivery signal. Watch for Dallas leading the others when reshoring activity is the driver.',
    methodology: 'Dallas Fed Texas Manufacturing Outlook Survey, Current Delivery Time Diffusion Index, seasonally adjusted (DTMSAMFRBDAL).',
  },
  {
    id: 'PPI_PULP',
    source: 'fred', sourceId: 'WPU0911',
    category: 'dc',
    label: 'PPI: Wood Pulp',
    shortLabel: 'Pulp PPI',
    unit: '', decimals: 1, freq: 'monthly', transform: 'level',
    release: 'BLS PPI, mid-month',
    direction: 'lower_better',
    longTermNormYears: 10,
    whyMatters: 'Wood pulp is the upstream input for containerboard / corrugated boxes. Pulp PPI leads corrugated box PPI by 1-2 quarters. Useful as an early warning for packaging-cost inflation that will hit DC opex within 6 months.',
    howToRead: 'Pulp YoY > 8% means expect corrugated PPI to follow up within 1-2 quarters. Falling pulp signals packaging cost relief in the pipeline.',
    methodology: 'BLS PPI series WPU0911 - Wood Pulp.',
  },

  // ---- INDUSTRIAL RE: REIT constituents (individual tickers) ----
  {
    id: 'PLD', source: 'yahoo', sourceId: ['PLD'],
    category: 'industrial-re',
    label: 'Prologis (PLD)', shortLabel: 'PLD',
    unit: '$', decimals: 2, freq: 'daily', transform: 'level',
    release: 'daily',
    direction: 'higher_better', longTermNormYears: 5,
    isTicker: true,
    whyMatters: 'Worlds largest industrial REIT - a public-market read on global goods-flow demand. Prologis stock often leads private-market industrial cap-rate moves by 6-12 months.',
    howToRead: 'Drawdown from peak > 20% means expect private cap rates to widen 50-100bps over next year. Outperformance vs S&P signals cap-rate compression cycle.',
    methodology: 'NYSE-listed Prologis Inc., daily adjusted close from Yahoo Finance.',
  },
  {
    id: 'REXR', source: 'yahoo', sourceId: ['REXR'],
    category: 'industrial-re',
    label: 'Rexford Industrial (REXR)', shortLabel: 'REXR',
    unit: '$', decimals: 2, freq: 'daily', transform: 'level',
    release: 'daily', direction: 'higher_better', longTermNormYears: 5,
    isTicker: true,
    whyMatters: 'Pure-play SoCal infill industrial. Direct read on LA/IE warehouse rents - entry point for ~40% of US containerized imports.',
    howToRead: 'Outperforms when SoCal port volumes rise; underperforms when freight diverts East Coast.',
    methodology: 'NYSE-listed Rexford Industrial Realty.',
  },
  {
    id: 'FR', source: 'yahoo', sourceId: ['FR'],
    category: 'industrial-re',
    label: 'First Industrial (FR)', shortLabel: 'FR',
    unit: '$', decimals: 2, freq: 'daily', transform: 'level',
    release: 'daily', direction: 'higher_better', longTermNormYears: 5,
    isTicker: true,
    whyMatters: 'Top-15 US logistics markets, well-diversified. National-average benchmark.',
    howToRead: 'Use as midpoint vs PLD (premium global) and STAG (secondary markets).',
    methodology: 'NYSE-listed First Industrial Realty Trust.',
  },
  {
    id: 'STAG', source: 'yahoo', sourceId: ['STAG'],
    category: 'industrial-re',
    label: 'STAG Industrial (STAG)', shortLabel: 'STAG',
    unit: '$', decimals: 2, freq: 'daily', transform: 'level',
    release: 'daily', direction: 'higher_better', longTermNormYears: 5,
    isTicker: true,
    whyMatters: 'Secondary/tertiary US markets. Read on inland distribution and non-gateway warehouse demand.',
    howToRead: 'Higher cap rate, more sensitive to financial conditions. Watch for credit-spread divergence vs PLD.',
    methodology: 'NYSE-listed STAG Industrial.',
  },
  {
    id: 'EGP', source: 'yahoo', sourceId: ['EGP'],
    category: 'industrial-re',
    label: 'EastGroup Properties (EGP)', shortLabel: 'EGP',
    unit: '$', decimals: 2, freq: 'daily', transform: 'level',
    release: 'daily', direction: 'higher_better', longTermNormYears: 5,
    isTicker: true,
    whyMatters: 'Sunbelt-focused industrial. Direct beneficiary of US population migration south and reshoring (TX/AZ semi + auto).',
    howToRead: 'Outperformance signals Sunbelt logistics demand outpacing national.',
    methodology: 'NYSE-listed EastGroup Properties.',
  },
  {
    id: 'TRNO', source: 'yahoo', sourceId: ['TRNO'],
    category: 'industrial-re',
    label: 'Terreno Realty (TRNO)', shortLabel: 'TRNO',
    unit: '$', decimals: 2, freq: 'daily', transform: 'level',
    release: 'daily', direction: 'higher_better', longTermNormYears: 5,
    isTicker: true,
    whyMatters: 'Coastal-only industrial REIT - six gateway markets. Highest land-value-per-foot in the basket. Most exposed to port volume cycles.',
    howToRead: 'Tracks port-proximate logistics rent - the most cyclical part of the industrial-RE complex.',
    methodology: 'NYSE-listed Terreno Realty.',
  },

  // ---- INDUSTRIAL RE: Cold Storage REITs ----
  {
    id: 'COLD', source: 'yahoo', sourceId: ['COLD'],
    category: 'industrial-re',
    label: 'Americold (COLD)', shortLabel: 'COLD',
    unit: '$', decimals: 2, freq: 'daily', transform: 'level',
    release: 'daily', direction: 'higher_better', longTermNormYears: 5,
    isTicker: true,
    whyMatters: 'Largest US cold-storage operator. Cold-chain real estate is a structurally tighter market than dry industrial - limited new supply, higher capex, regulated.',
    howToRead: 'Cold storage cycles less with general freight; more with food-supply and pharma. Watch alongside food PPI.',
    methodology: 'NYSE-listed Americold Realty Trust.',
  },
  {
    id: 'LINE', source: 'yahoo', sourceId: ['LINE'],
    category: 'industrial-re',
    label: 'Lineage (LINE)', shortLabel: 'LINE',
    unit: '$', decimals: 2, freq: 'daily', transform: 'level',
    release: 'daily', direction: 'higher_better', longTermNormYears: 2,
    isTicker: true,
    whyMatters: 'Worlds largest cold-storage operator. IPOd Jul 2024. Direct read on perishable goods supply chain.',
    howToRead: 'Newer listing - short trading history. Use alongside COLD for cold-chain signal.',
    methodology: 'NYSE-listed Lineage Inc., IPO July 2024.',
  },

  // ---- INDUSTRIAL RE: Self-Storage REITs ----
  {
    id: 'PSA', source: 'yahoo', sourceId: ['PSA'],
    category: 'industrial-re',
    label: 'Public Storage (PSA)', shortLabel: 'PSA',
    unit: '$', decimals: 2, freq: 'daily', transform: 'level',
    release: 'daily', direction: 'higher_better', longTermNormYears: 10,
    isTicker: true,
    whyMatters: 'Largest US self-storage REIT. Adjacent to last-mile / consumer warehousing. Demand cycles with home-buying activity and small-business inventory.',
    howToRead: 'Counter-cyclical defensive characteristics. Watch as a hedge against industrial REIT exposure.',
    methodology: 'NYSE-listed Public Storage.',
  },
  {
    id: 'EXR', source: 'yahoo', sourceId: ['EXR'],
    category: 'industrial-re',
    label: 'Extra Space Storage (EXR)', shortLabel: 'EXR',
    unit: '$', decimals: 2, freq: 'daily', transform: 'level',
    release: 'daily', direction: 'higher_better', longTermNormYears: 10,
    isTicker: true,
    whyMatters: 'Second-largest self-storage operator. More tech-forward than PSA - heavy use of revenue-management algorithms.',
    howToRead: 'Read on consumer storage demand and small-business inventory.',
    methodology: 'NYSE-listed Extra Space Storage.',
  },
  {
    id: 'CUBE', source: 'yahoo', sourceId: ['CUBE'],
    category: 'industrial-re',
    label: 'CubeSmart (CUBE)', shortLabel: 'CUBE',
    unit: '$', decimals: 2, freq: 'daily', transform: 'level',
    release: 'daily', direction: 'higher_better', longTermNormYears: 10,
    isTicker: true,
    whyMatters: 'Mid-size self-storage operator with urban concentration. Often a take-out target in consolidation cycles.',
    howToRead: 'Underperformance vs PSA/EXR can signal scale-disadvantage; outperformance often anticipates M&A.',
    methodology: 'NYSE-listed CubeSmart.',
  },

  // ---- INTERNATIONAL: nearshoring / chokepoints / carbon ----
  {
    id: 'BORDER_MX_TRUCKS',
    source: 'scrape:bts-borders',
    category: 'international',
    label: 'US-Mexico Border Truck Crossings',
    shortLabel: 'MX Trucks',
    unit: 'k', decimals: 0, freq: 'monthly', transform: 'level',
    release: 'BTS Border Crossing Statistics, monthly',
    direction: 'higher_better',
    longTermNormYears: 10,
    featured: true,
    whyMatters: 'Direct read on US-Mexico nearshoring. Cross-border truck volumes have grown 6-8% per year since 2020 as supply chains restructure away from China. Concentrated at Laredo, El Paso, Otay Mesa. Leading indicator of Mexican manufacturing reshoring activity by 6-12 months ahead of trade-balance data.',
    howToRead: 'YoY > +5% means nearshoring momentum intact. Below +2% signals deceleration; watch for Mexico-policy changes (tariffs, IMMEX program).',
    methodology: 'BTS Border Crossing/Entry Data, all US-Mexico ports, truck loaded plus empty crossings.',
  },
  {
    id: 'SUEZ_TRANSITS',
    source: 'scrape:imf-portwatch',
    sourceId: 'chokepoint1',
    category: 'international',
    label: 'Suez Canal Monthly Transits',
    shortLabel: 'Suez Transits',
    unit: 'ships', decimals: 0, freq: 'monthly', transform: 'level',
    release: 'IMF PortWatch, daily (monthly aggregate)',
    direction: 'higher_better',
    longTermNormYears: 5,
    whyMatters: 'Houthi/Red Sea attacks since late 2023 caused container lines to divert via Cape of Good Hope, adding 7-10 days and 15-25% to Asia-Europe voyage cost. Transit count is the cleanest single number on whether the canal route is functioning.',
    howToRead: 'Trending up means diversions easing, lanes normalizing. Trending down signals continued risk premium, watch container rates rising.',
    methodology: 'IMF PortWatch Daily_Chokepoints_Data, chokepoint1 (Suez Canal), n_total field summed by month. Based on AIS satellite data with 48-hour de-dup window.',
  },
  {
    id: 'PANAMA_TRANSITS',
    source: 'scrape:imf-portwatch',
    sourceId: 'chokepoint2',
    category: 'international',
    label: 'Panama Canal Monthly Transits',
    shortLabel: 'Panama Transits',
    unit: 'ships', decimals: 0, freq: 'monthly', transform: 'level',
    release: 'IMF PortWatch, daily (monthly aggregate)',
    direction: 'higher_better',
    longTermNormYears: 5,
    whyMatters: 'Drought in 2023-24 reduced daily transit allocations from 36 to 22 ships, raising slot-auction prices and driving cargo to East Coast / Gulf alternatives. Transit volume is the clean read on whether water-level constraints have eased.',
    howToRead: 'Approaching 36/day (~1080/month) means constraints eased. Below 28/day (~840/month) means tight; expect continued East Coast / Gulf routing premium.',
    methodology: 'IMF PortWatch Daily_Chokepoints_Data, chokepoint2 (Panama Canal), n_total summed by month.',
  },
  {
    id: 'EU_ETS_CARBON',
    source: 'yahoo',
    sourceId: 'KEUA',
    category: 'international',
    label: 'EU ETS Carbon Proxy (KEUA ETF)',
    shortLabel: 'EU ETS Proxy',
    unit: 'USD', decimals: 2, freq: 'daily', transform: 'level',
    release: 'NYSE Arca, daily',
    direction: 'lower_better',
    longTermNormYears: 4,
    whyMatters: 'Shipping fully phased into the EU Emissions Trading System: 40% of CO2 covered in 2024, 70% in 2025, 100% by 2026. KEUA is a pure-EUA ETF tracking the front-month EUA contract - daily liquid proxy when ICE/EEX direct feeds are paywalled.',
    howToRead: 'Rising trend means carriers will pass higher EUA cost into freight rates. Falling means carbon-cost pressure easing. Use change vs 4-year mean since absolute USD level is ETF NAV, not EUR/t.',
    methodology: 'KraneShares European Carbon Allowance Strategy ETF (KEUA) daily adjusted close from Yahoo Finance. Holds front-month EUA futures; tracks EUA spot closely (correlation > 0.95 since 2021 launch).',
  },
  {
    id: 'RESHORING_COUNT',
    source: 'scrape:reshoring',
    category: 'international',
    label: 'Reshoring Initiative Annual Job Count',
    shortLabel: 'Reshoring Jobs',
    unit: 'k', decimals: 0, freq: 'annual', transform: 'level',
    release: 'Reshoring Initiative, annual Q1',
    direction: 'higher_better',
    longTermNormYears: 10,
    whyMatters: 'Reshoring Initiative tracks announced jobs returning to / staying in the US (vs going offshore). Long-cycle structural signal - slower than border-crossings but a confirmation of the strategic shift.',
    howToRead: 'Above 350k/year means strong structural reshoring momentum. Below 200k/year is a slowdown, watch for policy reversal.',
    methodology: 'Reshoring Initiative annual report, total announced reshoring + foreign direct investment (FDI) jobs.',
  },
];

// Group lookups for the renderer.
export const INDICATORS_BY_CATEGORY = INDICATORS.reduce((acc, ind) => {
  (acc[ind.category] = acc[ind.category] || []).push(ind);
  return acc;
}, {});

export const INDICATORS_BY_ID = Object.fromEntries(INDICATORS.map(i => [i.id, i]));

// Source helpers for the refresh orchestrator.
export const INDICATORS_BY_SOURCE = INDICATORS.reduce((acc, ind) => {
  (acc[ind.source] = acc[ind.source] || []).push(ind);
  return acc;
}, {});
