// Indicator registry for the Economic Dashboard.
//
// Each entry describes one indicator: where to pull it, how to transform it,
// and how to frame it for a reader. The dashboard reads this registry,
// fetches each series from /api/fred (or a nowcast source), and renders cards
// driven entirely by these definitions.
//
// Fields:
//   id          : stable internal key (used in URLs for drill-downs)
//   source      : 'fred' | 'nowcast' (nowcast = external, wired in Phase 2)
//   fredId      : FRED series ID (for source='fred')
//   category    : 'growth' | 'inflation' | 'consumer' | 'housing'
//   label       : full display name
//   shortLabel  : compact label for dense grids
//   unit        : display unit suffix ('%', ' bps', 'K', '')
//   decimals    : display precision
//   freq        : 'daily' | 'weekly' | 'monthly' | 'quarterly'
//   transform   : 'level' | 'yoy' | 'mom' | 'mom_diff' | 'qoq_saar'
//                   level      : raw value
//                   yoy        : % change vs 12 months prior
//                   mom        : % change vs prior period
//                   mom_diff   : absolute change vs prior period (e.g. jobs added)
//                   qoq_saar   : quarter/quarter annualized, seasonally adjusted
//   release     : human-readable cadence note
//   context     : one-line plain-English description of what this measures / why it matters
//   direction   : 'higher_better' | 'lower_better' | 'target_band' | 'neutral'
//   target      : optional numeric target (for direction='target_band')
//   placeholder : if true, render as "coming soon" (Phase 2)
//
// Keep context strings tight (< 90 chars). Any detail should live on the
// drill-down page, not the card.

export const CATEGORIES = {
  growth:    { label: 'Growth',           accent: '#3b82f6' },
  inflation: { label: 'Inflation',        accent: '#ef4444' },
  consumer:  { label: 'Consumer & Labor', accent: '#10b981' },
  housing:   { label: 'Housing',          accent: '#a855f7' },
};

export const INDICATORS = [
  // ------------------------------------------------------------------ GROWTH
  {
    id: 'GDPC1',
    source: 'fred',
    fredId: 'GDPC1',
    category: 'growth',
    label: 'Real GDP (YoY)',
    shortLabel: 'Real GDP',
    unit: '%',
    decimals: 1,
    freq: 'quarterly',
    transform: 'yoy',
    release: 'Advance ~30 days after quarter end; revised twice',
    context: 'Headline output of the US economy. Sub-2% YoY historically signals below-trend growth.',
    direction: 'higher_better',
  },
  {
    id: 'GDPNOW',
    source: 'nowcast',
    category: 'growth',
    label: 'Atlanta Fed GDPNow',
    shortLabel: 'GDPNow',
    unit: '%',
    decimals: 1,
    freq: 'daily',
    transform: 'level',
    release: 'Updated several times per week through the quarter',
    context: 'Real-time nowcast of current-quarter Real GDP (QoQ SAAR). Model-based, not a forecast.',
    direction: 'higher_better',
    placeholder: true,
  },
  {
    id: 'T10Y3M',
    source: 'fred',
    fredId: 'T10Y3M',
    category: 'growth',
    label: '10Y–3M Treasury Spread',
    shortLabel: '10Y–3M Spread',
    unit: ' bps',
    decimals: 0,
    freq: 'daily',
    transform: 'level_bps', // FRED returns %; multiply by 100
    release: 'Daily',
    context: 'Yield-curve recession signal. Sustained inversion (<0) has preceded every US recession since 1960.',
    direction: 'higher_better',
  },
  {
    id: 'INDPRO',
    source: 'fred',
    fredId: 'INDPRO',
    category: 'growth',
    label: 'Industrial Production (YoY)',
    shortLabel: 'Ind. Production',
    unit: '%',
    decimals: 1,
    freq: 'monthly',
    transform: 'yoy',
    release: 'Mid-month, prior month',
    context: 'Output of factories, mines, utilities. Cyclical proxy for the goods economy (since ISM left FRED in 2021).',
    direction: 'higher_better',
  },
  {
    id: 'EMPIRE',
    source: 'fred',
    fredId: 'GACDISA066MSFRBNY',
    category: 'growth',
    label: 'Empire State Manufacturing Index',
    shortLabel: 'Empire State',
    unit: '',
    decimals: 1,
    freq: 'monthly',
    transform: 'level',
    release: 'Mid-month, current month (earliest US manufacturing reading)',
    context: 'NY Fed diffusion index. >0 expansion, <0 contraction. First US manufacturing datapoint each month.',
    direction: 'higher_better',
  },

  // --------------------------------------------------------------- INFLATION
  {
    id: 'PCEPILFE',
    source: 'fred',
    fredId: 'PCEPILFE',
    category: 'inflation',
    label: 'Core PCE (YoY)',
    shortLabel: 'Core PCE',
    unit: '%',
    decimals: 2,
    freq: 'monthly',
    transform: 'yoy',
    release: 'End of month, prior month',
    context: "Fed's preferred inflation gauge. Target 2.0%. Excludes food & energy.",
    direction: 'target_band',
    target: 2.0,
  },
  {
    id: 'CPILFESL',
    source: 'fred',
    fredId: 'CPILFESL',
    category: 'inflation',
    label: 'Core CPI (YoY)',
    shortLabel: 'Core CPI',
    unit: '%',
    decimals: 2,
    freq: 'monthly',
    transform: 'yoy',
    release: 'Mid-month, prior month',
    context: 'Consumer price inflation ex food & energy. Typically runs ~0.4ppt above Core PCE.',
    direction: 'target_band',
    target: 2.0,
  },
  {
    id: 'CLEVELAND_NOWCAST',
    source: 'nowcast',
    category: 'inflation',
    label: 'Cleveland Fed Inflation Nowcast',
    shortLabel: 'Cleveland Nowcast',
    unit: '%',
    decimals: 2,
    freq: 'daily',
    transform: 'level',
    release: 'Updated daily',
    context: 'Live nowcast for next CPI / PCE release. Updated as new daily data lands.',
    direction: 'target_band',
    target: 2.0,
    placeholder: true,
  },
  {
    id: 'STICKY',
    source: 'fred',
    fredId: 'CORESTICKM159SFRBATL',
    category: 'inflation',
    label: 'Atlanta Sticky-Price CPI (YoY)',
    shortLabel: 'Sticky CPI',
    unit: '%',
    decimals: 2,
    freq: 'monthly',
    transform: 'level', // this series is already published as 12-mo pct change
    release: 'Mid-month, with CPI',
    context: 'Subset of CPI basket with slow-moving prices. A cleaner read on inflation persistence than headline.',
    direction: 'target_band',
    target: 2.0,
  },
  {
    id: 'T5YIFR',
    source: 'fred',
    fredId: 'T5YIFR',
    category: 'inflation',
    label: '5Y5Y Forward Inflation',
    shortLabel: '5Y5Y Breakeven',
    unit: '%',
    decimals: 2,
    freq: 'daily',
    transform: 'level',
    release: 'Daily',
    context: "Market's pricing of average inflation 5–10y ahead. The Fed watches this for anchored expectations.",
    direction: 'target_band',
    target: 2.0,
  },

  // ------------------------------------------------------- CONSUMER & LABOR
  {
    id: 'UNRATE',
    source: 'fred',
    fredId: 'UNRATE',
    category: 'consumer',
    label: 'Unemployment Rate',
    shortLabel: 'Unemployment',
    unit: '%',
    decimals: 1,
    freq: 'monthly',
    transform: 'level',
    release: 'First Friday of month, prior month',
    context: 'Sahm Rule: 0.5ppt rise over 3mo-avg trough historically = recession underway.',
    direction: 'lower_better',
  },
  {
    id: 'PAYEMS',
    source: 'fred',
    fredId: 'PAYEMS',
    category: 'consumer',
    label: 'Nonfarm Payrolls (MoM change)',
    shortLabel: 'Payrolls (MoM)',
    unit: 'K',
    decimals: 0,
    freq: 'monthly',
    transform: 'mom_diff_k', // diff in thousands (FRED publishes in thousands of persons)
    release: 'First Friday of month, prior month',
    context: 'Jobs added last month. Breakeven for stable U-rate is ~100–150K given labor-force growth.',
    direction: 'higher_better',
  },
  {
    id: 'AHE',
    source: 'fred',
    fredId: 'CES0500000003',
    category: 'consumer',
    label: 'Avg Hourly Earnings (YoY)',
    shortLabel: 'Wage Growth',
    unit: '%',
    decimals: 1,
    freq: 'monthly',
    transform: 'yoy',
    release: 'First Friday of month, with payrolls',
    context: 'Nominal wage growth. Real wages = this minus CPI YoY (Phase 2 will derive and show).',
    direction: 'higher_better',
  },
  {
    id: 'RRSFS',
    source: 'fred',
    fredId: 'RRSFS',
    category: 'consumer',
    label: 'Real Retail Sales (YoY)',
    shortLabel: 'Real Retail',
    unit: '%',
    decimals: 1,
    freq: 'monthly',
    transform: 'yoy',
    release: 'Mid-month, prior month',
    context: 'Inflation-adjusted consumer spending on goods. ~70% of US GDP is consumption.',
    direction: 'higher_better',
  },
  {
    id: 'IC4WSA',
    source: 'fred',
    fredId: 'IC4WSA',
    category: 'consumer',
    label: 'Initial Jobless Claims (4wk MA)',
    shortLabel: 'Jobless Claims',
    unit: 'K',
    decimals: 0,
    freq: 'weekly',
    transform: 'level_k', // FRED publishes in persons; render as thousands
    release: 'Every Thursday',
    context: 'Real-time labor-market signal. Sustained move above ~300K has historically marked turning points.',
    direction: 'lower_better',
  },
  {
    id: 'DRCCLACBS',
    source: 'fred',
    fredId: 'DRCCLACBS',
    category: 'consumer',
    label: 'Credit Card Delinquency Rate',
    shortLabel: 'CC Delinquency',
    unit: '%',
    decimals: 2,
    freq: 'quarterly',
    transform: 'level',
    release: 'Quarterly, ~2 months after quarter end',
    context: 'Consumer balance-sheet stress. Rising delinquencies lead consumer-spending weakness by 1–2 quarters.',
    direction: 'lower_better',
  },

  // ---------------------------------------------------------------- HOUSING
  {
    id: 'PERMIT',
    source: 'fred',
    fredId: 'PERMIT',
    category: 'housing',
    label: 'Building Permits (YoY)',
    shortLabel: 'Permits',
    unit: '%',
    decimals: 1,
    freq: 'monthly',
    transform: 'yoy',
    release: 'Mid-month, prior month',
    context: 'Leading housing indicator: permits precede starts by 1–2 months.',
    direction: 'higher_better',
  },
  {
    id: 'HOUST',
    source: 'fred',
    fredId: 'HOUST',
    category: 'housing',
    label: 'Housing Starts (YoY)',
    shortLabel: 'Starts',
    unit: '%',
    decimals: 1,
    freq: 'monthly',
    transform: 'yoy',
    release: 'Mid-month, prior month',
    context: 'New residential construction begun. A direct GDP contributor via residential investment.',
    direction: 'higher_better',
  },
  {
    id: 'EXHOSLUS',
    source: 'fred',
    fredId: 'EXHOSLUSM495S',
    category: 'housing',
    label: 'Existing Home Sales (YoY)',
    shortLabel: 'Existing Sales',
    unit: '%',
    decimals: 1,
    freq: 'monthly',
    transform: 'yoy',
    release: 'Third week of month, prior month',
    context: '~90% of total home sales. Weakness here is the clearest transmission of higher mortgage rates.',
    direction: 'higher_better',
  },
  {
    id: 'HSN1F',
    source: 'fred',
    fredId: 'HSN1F',
    category: 'housing',
    label: 'New Home Sales (YoY)',
    shortLabel: 'New Home Sales',
    unit: '%',
    decimals: 1,
    freq: 'monthly',
    transform: 'yoy',
    release: 'End of month, prior month',
    context: 'Sales of newly-built single-family homes. Volatile but a direct read on builder demand.',
    direction: 'higher_better',
  },
  {
    id: 'MORTGAGE30US',
    source: 'fred',
    fredId: 'MORTGAGE30US',
    category: 'housing',
    label: '30Y Fixed Mortgage Rate',
    shortLabel: '30Y Mortgage',
    unit: '%',
    decimals: 2,
    freq: 'weekly',
    transform: 'level',
    release: 'Every Thursday (Freddie Mac PMMS)',
    context: 'Marginal cost of a new mortgage. Each 100bp move changes monthly payment on a $400K loan by ~$260.',
    direction: 'lower_better',
  },
  {
    id: 'CSUSHPISA',
    source: 'fred',
    fredId: 'CSUSHPISA',
    category: 'housing',
    label: 'Case-Shiller Home Price Index (YoY)',
    shortLabel: 'Case-Shiller HPI',
    unit: '%',
    decimals: 1,
    freq: 'monthly',
    transform: 'yoy',
    release: 'Last Tuesday of month, 2-month lag',
    context: 'Repeat-sales national home price index. Lags sales volume turns by ~6 months.',
    direction: 'neutral',
  },
];

// Convenience lookups
export const INDICATORS_BY_ID = Object.fromEntries(INDICATORS.map(i => [i.id, i]));
export const INDICATORS_BY_CATEGORY = INDICATORS.reduce((acc, ind) => {
  (acc[ind.category] ||= []).push(ind);
  return acc;
}, {});
